### ISSUE TITLE
is there any plan to release the code for preprocess data or preprocessed data?

### ISSUE THREAD

**Issue by annymie** [chiahsuan156/DST-as-Prompting#3]

**Comment by chiahsuan156** [comment]
Hi sorry for the delay. I am planning to release it within the next week. thanks!

**Comment by aa452948257** [comment]
Sorry, is there possibly to release the code for preprocess data or preprocessed data?

**Comment by aa452948257** [comment]
T.T Sorry, can you offer me a code for preprocessing data, I have sent you an e-mail, but you dont respones me.

**Comment by AibibulaAtawula** [comment]
is there possibly to release the code for preprocess data or preprocessed data? Thank u

**Comment by daniellibin** [comment]
> is there possibly to release the code for preprocess data or preprocessed data? Thank u

hi bro,
do u get the  preprocess data or data?
Thanks

**Comment by AibibulaAtawula** [comment]
regrettably,  am not
