### ISSUE TITLE
To confirm 2 questions made me confused in the paper.

### ISSUE THREAD

**Issue by Young1993** [chiahsuan156/DST-as-Prompting#4]
Hi,

I think this is a very interesting work and I have two questions want to check:

1.  **For Schema-Based Prompt DST w/ Independent Decoding**,  during the inference stage, does the model predict the domain, slot, and value in parallel or in order?  I'm confused about whether the T5 needs to predict 8 times for 8 domains in each sample. Then, it predicts the slots in each domain. Finally, T5 has to predict the slot value many many times? How to get all this in one go?
2. The case with desc impresses me a lot, where the model can modify the 4:45 PM to 16:45, that's quite amazing, how the model makes it?
![image](https://user-images.githubusercontent.com/11806958/155258151-f9896100-df93-42e5-89f9-0925dc2d8d6c.png)

Looking forward to your reply.

Best

**Comment by chiahsuan156** [comment]
Hi, thanks for the interest!

1. You are right about independent decoding. Let's say there are 8 domains and each domain has 6 slots. Then for a single turn, the model needs to run predictions 8 * 6 = 48 times. This is, of course, totally parallel (no order is required)

2. In this example, the model is not just copying from the inputs. Our hypothesis is that the model can leverage descriptions and knows that this is a time-related value to predict.

**Comment by Young1993** [comment]
OK, THX!
