### ISSUE TITLE
Is there custom `Schema.json` for MultiWOZ?

### ISSUE THREAD

**Issue by 0ys** [chiahsuan156/DST-as-Prompting#8]
Hi, 

I am trying to use `eval.py`, but I am experiencing an error that the file cannot be found. (example below)
`FileNotFoundError: [Errno 2] No such file or directory: 'multiwoz/data/MultiWOZ_2.2/test/schema.json'`

MultiWOZ official git does not have the `schema.json` in _data/MultiWOZ_2.2/test_, _data/MultiWOZ_2.2/train_
So I wonder if you use a customized Schema.json files for test and train dataset.

If So, could you share the customized schema file?
Or just brief Schema information will help.

I am grateful for your great work.
I look forward to hearing from you

Regards,
Yeseul

**Comment by chiahsuan156** [comment]
Hi Sorry for the late response! No there is no "customed" schema file. 
It's the file in MWOZ official repo and it is used in every subset (training, testing...)
https://github.com/budzianowski/multiwoz/blob/master/data/MultiWOZ_2.2/schema.json
